### ISSUE TITLE
사용자 CRUD

### ISSUE THREAD

**Issue by marshot9420** [NomadHotPlaces/nomadhotplaces-backend#1]
# 사용자 CRUD

## 프로젝트 추출물

- 👉 [ERDCloud](https://www.erdcloud.com/d/GPQWKfKoewF384vHF)

사용자 ERD

## 요구사항

- 사용자는 회원가입을 통해 계정을 생성할 수 있음
- 사용자 인증 방식은 카카오, 네이버, 깃허브, 구글을 통한 OAuth와 JWT 인증 방식
- 로그인은 이메일을 통해 로그인 할 수 있어야 함.
- 사용자는 본인의 프로필 사진을 추가할 수 있고, 자신의 기본적인 프로필 정보와 비밀번호를 변경할 수 있어야 함
- 이메일 인증 방식을 통한 회원가입이 구현되어야 됨(악성 유저 방지를 위한 최소한의 장치)
- 사용자의 역할(role)은 관리자(ADMIN)와 일반 사용자(USER)로 나뉨
- 사용자는 자신이 원할 때 언제든지 회원탈퇴 가능
- 회원가입 시 사용자의 역할은 기본적으로 사용자(USER)가 되어야 하며, 관리자 계정은 별도로 생성

## TODOs

- [ ] 사용자 엔티티 
- [ ] 이메일 회원가입 기능
- [ ] Local Strategy와 Local Guard
- [ ] currentuser 데코레이터
- [ ] JWT Access 토큰 발행 로직
- [ ] JWT Refresh 토큰 발행 로직
- [ ] 이메일 로그인 기능
- [ ] 카카오 회원가입/로그인
- [ ] 네이버 회원가입/로그인
- [ ] 구글 회원가입/로그인
- [ ] 깃허브 회원가입/로그인
- [ ] JWT User validate
- [ ] 토큰 Refresh 기능
- [ ] 로그아웃 기능
- [ ] 비밀번호 변경
- [ ] 회원 본인 정보 조회
- [ ] 회원 본인 정보 수정
- [ ] 회원탈퇴

## API 엔드포인트

Auth 관련

- **회원가입**: POST => `/api/auth/join`
- **로그인**: POST => `/api/auth/login`
- **로그아웃**: POST => `/api/auth/logout`
- **카카오 회원가입/로그인**: GET => `/api/auth/kakao`
- **카카오 OAuth 콜백**: GET => `/api/auth/kakao/oauth`
- **네이버 회원가입/로그인**: GET => `/api/auth/naver`
- **네이버 OAuth 콜백**: GET => `/api/auth/naver/oauth`
- **구글 회원가입/로그인**: GET => `/api/auth/google`
- **구글 OAuth 콜백**: GET => `/api/auth/google/oauth`
- **깃허브 회원가입/로그인**: GET => `/api/auth/github`
- **깃허브 OAuth 콜백**: GET => `/api/auth/github/oauth`
- **회원탈퇴**: DELETE => `/api/auth/local`
- **Access 토큰 갱신**: GET => `/api/auth/refresh`

User 관련

- **본인 정보 조회**: GET => `/api/users/me`
- **본인 정보 수정**: PATCH => `/api/users/me`
- **비밀번호 변경**: PATCH => `/api/users/me/change-password`
